In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [2]:
from sklearn.preprocessing import OneHotEncoder

In [3]:
df = pd.read_csv('parks_busyness_weather.csv')

C:\Users\Justh\AppData\Local\Temp\ipykernel_3848\956686395.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('parks_busyness_weather.csv')


In [4]:
df.head()

park_id         park_name      park_area  year  month  day  hour  \
0   PK101  Inwood Hill Park  784904.717278  2022      1    1    11   
1   PK101  Inwood Hill Park  784904.717278  2022      1    1    17   
2   PK101  Inwood Hill Park  784904.717278  2022      1    1    19   
3   PK101  Inwood Hill Park  784904.717278  2022      1   10    12   
4   PK101  Inwood Hill Park  784904.717278  2022      1   10    13   

   day_of_week  weekend  season  ...  taxi_zone_ids                taxi_zones  \
0            5        1       4  ...            243  Washington Heights North   
1            5        1       4  ...            243  Washington Heights North   
2            5        1       4  ...            243  Washington Heights North   
3            0        0       4  ...            243  Washington Heights North   
4            0        0       4  ...            243  Washington Heights North   

                                            geometry             datetime  \
0  POLYGON ((-73.9320015 40.86963009999998, -73.9...  2022-01-01 11:00:00   
1  POLYGON ((-73.9320015 40.86963009999998, -73.9...  2022-01-01 17:00:00   
2  POLYGON ((-73.9320015 40.86963009999998, -73.9...  2022-01-01 19:00:00   
3  POLYGON ((-73.9320015 40.86963009999998, -73.9...  2022-01-10 12:00:00   
4  POLYGON ((-73.9320015 40.86963009999998, -73.9...  2022-01-10 13:00:00   

                dt_iso   temp temp_min temp_max rain_1h rain_3h  
0  2022-01-01 11:00:00  10.21     9.22    11.00    0.25     0.0  
1  2022-01-01 17:00:00  12.12    11.47    12.78    0.38     0.0  
2  2022-01-01 19:00:00  12.16    11.45    12.81    0.25     0.0  
3  2022-01-10 12:00:00  -1.61    -2.21    -0.78    0.00     0.0  
4  2022-01-10 13:00:00  -1.88    -3.21    -1.22    0.00     0.0  

[5 rows x 26 columns]

In [ ]:
# Separate features and target
X = df.drop(columns='target')
y = df['target']

In [5]:
training_set,testing_set=train_test_split(df,test_size=0.3, random_state=12)

In [6]:
weekend_2D = training_set['weekend'].values.reshape(-1, 1)
print(weekend_2D)
encoder_weekend=OneHotEncoder()
encoder_weekend.fit(weekend_2D)
encoded_weekend = encoder_weekend.transform(weekend_2D)

[[0]
 [0]
 [1]
 ...
 [0]
 [0]
 [0]]


In [7]:
season_2D = training_set['season'].values.reshape(-1, 1)
print(season_2D)
encoder_season=OneHotEncoder()
encoder_season.fit(season_2D)
encoded_season = encoder_season.transform(season_2D)

[[2]
 [1]
 [2]
 ...
 [1]
 [1]
 [3]]


In [8]:
holiday_2D = training_set['isHoliday?'].values.reshape(-1, 1)
print(holiday_2D)
encoder_holiday=OneHotEncoder()
encoder_holiday.fit(holiday_2D)
encoded_holiday = encoder_holiday.transform(holiday_2D)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [9]:

trainset_rf_encoded_weekend_df = pd.DataFrame(encoded_weekend.toarray(), columns=encoder_weekend.get_feature_names_out(['weekend']))
trainset_rf_encoded_season_df=pd.DataFrame(encoded_season.toarray(),columns=encoder_season.get_feature_names_out(['season']))
trainset_rf_encoded_holiday_df=pd.DataFrame(encoded_holiday.toarray(),columns=encoder_holiday.get_feature_names_out(['isHoliday?']))
#trainset_rf_encoded_month_df=pd.DataFrame(encoded_month.toarray(),columns=encoder_month.get_feature_names_out(['month']))
#trainset_rf_encoded_day_df=pd.DataFrame(encoded_day.toarray(),columns=encoder_day.get_feature_names_out(['day']))
#trainset_rf_encoded_hour_df=pd.DataFrame(encoded_hour.toarray(),columns=encoder_hour.get_feature_names_out(['hour']))


In [10]:

training_set.reset_index(drop=True, inplace=True)
trainset_rf_encoded_weekend_df.reset_index(drop=True, inplace=True)
trainset_rf_encoded_season_df.reset_index(drop=True, inplace=True)
trainset_rf_encoded_holiday_df.reset_index(drop=True, inplace=True)
#trainset_rf_encoded_month_df.reset_index(drop=True, inplace=True)
#trainset_rf_encoded_day_df.reset_index(drop=True, inplace=True)
#trainset_rf_encoded_hour_df.reset_index(drop=True, inplace=True)



In [11]:
training_set

park_id                      park_name     park_area  year  month  day  \
0         PK93             Hells Kitchen Park   2230.508728  2022      9    8   
1         PK24     Abraham Lincoln Playground   4325.672818  2022      4   21   
2        PK106     Jacob H. Schiff Playground  15448.481391  2022     11    5   
3         PK58             Corlears Hook Park  20899.230028  2022      9   10   
4        PK221               West Thames Park   8692.216750  2022      4   25   
...        ...                            ...           ...   ...    ...  ...   
235450   PK224                  Zuccotti Park   3439.798590  2022      3   20   
235451   PK125                Mannahatta Park   2202.864541  2022      4    3   
235452   PK129  Martin Luther King Playground   3821.679520  2022      4    1   
235453    PK51                   Clinton Cove   9144.443743  2022      4   13   
235454    PK40                    Bryant Park  23366.186815  2022      6   16   

        hour  day_of_week  weekend  season  ...  taxi_zone_ids  \
0         11            3        0       2  ...             48   
1         17            3        0       1  ...             74   
2          1            5        1       2  ...            152   
3         16            5        1       2  ...            232   
4         17            0        0       1  ...             13   
...      ...          ...      ...     ...  ...            ...   
235450     3            6        1       1  ...            261   
235451     8            6        1       1  ...             87   
235452    23            4        0       1  ...             41   
235453    21            2        0       1  ...             50   
235454    21            3        0       3  ...            164   

                      taxi_zones  \
0                   Clinton East   
1              East Harlem North   
2                 Manhattanville   
3        Two Bridges/Seward Park   
4              Battery Park City   
...                          ...   
235450        World Trade Center   
235451  Financial District North   
235452            Central Harlem   
235453              Clinton West   
235454             Midtown South   

                                                 geometry  \
0       POLYGON ((-73.9929256 40.7628175, -73.9925971 ...   
1       POLYGON ((-73.9365256 40.8121742, -73.9367819 ...   
2       POLYGON ((-73.9528181 40.820451699999985, -73....   
3       POLYGON ((-73.9779298 40.7124123, -73.9779042 ...   
4       POLYGON ((-74.0158126 40.7078747, -74.015861 4...   
...                                                   ...   
235450  POLYGON ((-74.0106724 40.7091447, -74.01066820...   
235451  MULTIPOLYGON (((-74.00726890000001 40.7051467,...   
235452  POLYGON ((-73.9503497 40.8006541, -73.9499105 ...   
235453  POLYGON ((-73.995826 40.7705802, -73.9957988 4...   
235454  POLYGON ((-73.984804 40.7535787, -73.9840853 4...   

                   datetime               dt_iso   temp temp_min temp_max  \
0       2022-09-08 11:00:00  2022-09-08 11:00:00  17.95    16.79    19.22   
1       2022-04-21 17:00:00  2022-04-21 17:00:00  13.79    12.78    14.23   
2       2022-11-05 01:00:00  2022-11-05 01:00:00  17.59    16.68    18.12   
3       2022-09-10 16:00:00  2022-09-10 16:00:00  26.13    24.78    27.23   
4       2022-04-25 17:00:00  2022-04-25 17:00:00  13.76    12.00    14.79   
...                     ...                  ...    ...      ...      ...   
235450  2022-03-20 03:00:00  2022-03-20 03:00:00  15.68    14.79    16.46   
235451  2022-04-03 08:00:00  2022-04-03 08:00:00   6.13     4.78     7.00   
235452  2022-04-01 23:00:00  2022-04-01 23:00:00   8.36     7.25     8.79   
235453  2022-04-13 21:00:00  2022-04-13 21:00:00  19.01    17.67    20.79   
235454  2022-06-16 21:00:00  2022-06-16 21:00:00  21.11    20.46    21.79   

       rain_1h rain_3h  
0         0.00    0.00  
1         0.00    0.00  
2         0.00    0.00  
3         0.00    0.00  
4         0.00    0.00  


In [12]:
training_set= pd.concat([training_set, trainset_rf_encoded_weekend_df, trainset_rf_encoded_season_df,trainset_rf_encoded_holiday_df], axis=1)


In [13]:
mlp_features= [ 'weekend_0', 'weekend_1', 'season_1', 'season_2', 'season_3',
       'season_4', 'isHoliday?_0', 'isHoliday?_1','rain_1h','rain_3h']


x_train=training_set[mlp_features]
y_train=training_set['park_busyness']

print("\nDescriptive features in X:\n", x_train)
print("\nTarget feature in y:\n", y_train)


Descriptive features in X:
         weekend_0  weekend_1  season_1  season_2  season_3  season_4  \
0             1.0        0.0       0.0       1.0       0.0       0.0   
1             1.0        0.0       1.0       0.0       0.0       0.0   
2             0.0        1.0       0.0       1.0       0.0       0.0   
3             0.0        1.0       0.0       1.0       0.0       0.0   
4             1.0        0.0       1.0       0.0       0.0       0.0   
...           ...        ...       ...       ...       ...       ...   
235450        0.0        1.0       1.0       0.0       0.0       0.0   
235451        0.0        1.0       1.0       0.0       0.0       0.0   
235452        1.0        0.0       1.0       0.0       0.0       0.0   
235453        1.0        0.0       1.0       0.0       0.0       0.0   
235454        1.0        0.0       0.0       0.0       1.0       0.0   

        isHoliday?_0  isHoliday?_1  rain_1h  rain_3h  
0                1.0           0.0     0.00     0.0

In [16]:
# Apply PCA to reduce the dimensionality
pca = PCA(n_components=0.95)  # Retain 95% of variance
X_pca = pca.fit_transform(x_train)


In [ ]:
# Initialize the MLP Regressor
mlp = MLPRegressor(hidden_layer_sizes=(100, 50,25), max_iter=1000, random_state=12)

# Train the model
mlp.fit(x_train, y_train)


MLPRegressor(hidden_layer_sizes=(100, 50, 25), max_iter=1000, random_state=12)

In [ ]:
# Make predictions on the test set
prediction = mlp.predict(x_train)


In [ ]:
prediction

array([0.40373717, 0.43814396, 0.40576743, ..., 0.43814396, 0.43814396,
       0.40538768])

In [ ]:
# Predicted class labels for all examples, 
# using the trained model, on in-sample data (same sample used for training and test)
mlp_predictions = mlp.predict(x_train)
df_true_vs_rfr_predicted = pd.DataFrame({'ActualClass': y_train, 'PredictedClass': mlp_predictions})
df_true_vs_rfr_predicted[:10]

ActualClass  PredictedClass
0     0.035355        0.403737
1     0.022821        0.438144
2     0.015626        0.405767
3     0.073915        0.405767
4     0.038035        0.438144
5     0.099902        0.438144
6     0.014340        0.414763
7     0.319305        0.414763
8     0.131248        0.438144
9     0.047536        0.412023

In [ ]:
# Evaluate the model
mse = mean_squared_error(y_train, mlp_predictions)
rmse = mse ** 0.5
r2 = r2_score(y_train, mlp_predictions)

print(f"Mean Squared Error: {mse}")
print(f"Root Mean Squared Error: {rmse}")
print(f"R-squared: {r2}")

Mean Squared Error: 5.727547118751605
Root Mean Squared Error: 2.393229432952805
R-squared: 0.00013596219083622518
